### PR TITLE
Updated library to target element `textContent` property

### PR DESCRIPTION
**Pull request by sachamasry**
Added functionality to target HTML element `textContent` property, in addition to element attributes.

### CODE REVIEW

**Comment by BartOtten** [comment]
Hi @sachamasry, please rebase on phoenix_live_head as I have formatted the files with Deno. The resulting diff will be much smaller and easier to discuss.

**Comment by sachamasry** [comment]
Thank you! I will only be able to try this in a day, and will let you know.

**Comment by BartOtten** [comment]
Hi Sasha, hope all is well. Any updates on this ticket?

**Comment by sachamasry** [comment]
Hi Bart,

I apologise for my delay in getting back to you—I had several fires to fight this week.

Looking through the `main` branch, I see no difference apart from the updated formatting; just to be clear, are you asking me to update to this formatting and then create a new PR (similar functionally to the prior one) on top of this? If so, I can get this done tomorrow.

**Comment by BartOtten** [comment]
Yes, that is what I meant. Can reuse / update this PR with command ‘git
rebase’ followed by ‘git push’. There should be no merge conflicts.

Let me know if you need any assistance; I am glad to help.

Op za 30 nov 2024 om 01:00 schreef Sacha El Masry ***@***.***>

> Hi Bart,
>
> I apologise for my delay in getting back to you—I had several fires to
> fight this week.
>
> Looking through the `main` branch, I see no difference apart from the
> updated formatting; just to be clear, are you asking me to update to this
> formatting and then create a new PR (similar functionally to the prior one)
> on top of this? If so, I can get this done tomorrow.
>

**Comment by sachamasry** [comment]
Hi Bart, I think I've now done that and created a new PR.

**Pull request closed without merging**
